#!/usr/bin/env python3
"""Add missing ACT 1 SCENE 7 to macbeth_notes_cleaned_play.json"""
import json
import os

# ACT 1 SCENE 7 content (Macbeth's castle - "If it were done" soliloquy)
# From https://shakespeare.mit.edu/macbeth/macbeth.1.7.html
ACT_1_SCENE_7 = {
    "1": {"play": "[Hautboys and torches. Enter a Sewer, and divers Servants with dishes and service, and pass over the stage. Then enter MACBETH]", "notes": []},
    "2": {"play": "MACBETH: If it were done when 'tis done, then 'twere well", "notes": []},
    "3": {"play": "It were done quickly: if the assassination", "notes": []},
    "4": {"play": "Could trammel up the consequence, and catch", "notes": []},
    "5": {"play": "With his surcease success; that but this blow", "notes": []},
    "6": {"play": "Might be the be-all and the end-all here,", "notes": []},
    "7": {"play": "But here, upon this bank and shoal of time,", "notes": []},
    "8": {"play": "We'ld jump the life to come. But in these cases", "notes": []},
    "9": {"play": "We still have judgment here; that we but teach", "notes": []},
    "10": {"play": "Bloody instructions, which, being taught, return", "notes": []},
    "11": {"play": "To plague the inventor: this even-handed justice", "notes": []},
    "12": {"play": "Commends the ingredients of our poison'd chalice", "notes": []},
    "13": {"play": "To our own lips. He's here in double trust;", "notes": []},
    "14": {"play": "First, as I am his kinsman and his subject,", "notes": []},
    "15": {"play": "Strong both against the deed; then, as his host,", "notes": []},
    "16": {"play": "Who should against his murderer shut the door,", "notes": []},
    "17": {"play": "Not bear the knife myself. Besides, this Duncan", "notes": []},
    "18": {"play": "Hath borne his faculties so meek, hath been", "notes": []},
    "19": {"play": "So clear in his great office, that his virtues", "notes": []},
    "20": {"play": "Will plead like angels, trumpet-tongued, against", "notes": []},
    "21": {"play": "The deep damnation of his taking-off;", "notes": []},
    "22": {"play": "And pity, like a naked new-born babe,", "notes": []},
    "23": {"play": "Striding the blast, or heaven's cherubim, horsed", "notes": []},
    "24": {"play": "Upon the sightless couriers of the air,", "notes": []},
    "25": {"play": "Shall blow the horrid deed in every eye,", "notes": []},
    "26": {"play": "That tears shall drown the wind. I have no spur", "notes": []},
    "27": {"play": "To prick the sides of my intent, but only", "notes": []},
    "28": {"play": "Vaulting ambition, which o'erleaps itself", "notes": []},
    "29": {"play": "And falls on the other.", "notes": []},
    "30": {"play": "[Enter LADY MACBETH]", "notes": []},
    "31": {"play": "LADY MACBETH: How now! what news?", "notes": []},
    "32": {"play": "MACBETH: He has almost supp'd: why have you left the chamber?", "notes": []},
    "33": {"play": "LADY MACBETH: Hath he ask'd for me?", "notes": []},
    "34": {"play": "MACBETH: Know you not he has?", "notes": []},
    "35": {"play": "LADY MACBETH: We will proceed no further in this business:", "notes": []},
    "36": {"play": "He hath honour'd me of late; and I have bought", "notes": []},
    "37": {"play": "Golden opinions from all sorts of people,", "notes": []},
    "38": {"play": "Which would be worn now in their newest gloss,", "notes": []},
    "39": {"play": "Not cast aside so soon.", "notes": []},
    "40": {"play": "MACBETH: Was the hope drunk", "notes": []},
    "41": {"play": "Wherein you dress'd yourself? hath it slept since?", "notes": []},
    "42": {"play": "And wakes it now, to look so green and pale", "notes": []},
    "43": {"play": "At what it did so freely? From this time", "notes": []},
    "44": {"play": "Such I account thy love. Art thou afeard", "notes": []},
    "45": {"play": "To be the same in thine own act and valour", "notes": []},
    "46": {"play": "As thou art in desire? Wouldst thou have that", "notes": []},
    "47": {"play": "Which thou esteem'st the ornament of life,", "notes": []},
    "48": {"play": "And live a coward in thine own esteem,", "notes": []},
    "49": {"play": "Letting 'I dare not' wait upon 'I would,'", "notes": []},
    "50": {"play": "Like the poor cat i' the adage?", "notes": []},
    "51": {"play": "LADY MACBETH: Prithee, peace: I dare do all that may become a man;", "notes": []},
    "52": {"play": "Who dares do more is none.", "notes": []},
    "53": {"play": "MACBETH: What beast was't, then,", "notes": []},
    "54": {"play": "That made you break this enterprise to me?", "notes": []},
    "55": {"play": "When you durst do it, then you were a man;", "notes": []},
    "56": {"play": "And, to be more than what you were, you would", "notes": []},
    "57": {"play": "Be so much more the man. Nor time nor place", "notes": []},
    "58": {"play": "Did then adhere, and yet you would make both:", "notes": []},
    "59": {"play": "They have made themselves, and that their fitness now", "notes": []},
    "60": {"play": "Does unmake you. I have given suck, and know", "notes": []},
    "61": {"play": "How tender 'tis to love the babe that milks me:", "notes": []},
    "62": {"play": "I would, while it was smiling in my face,", "notes": []},
    "63": {"play": "Have pluck'd my nipple from his boneless gums,", "notes": []},
    "64": {"play": "And dash'd the brains out, had I so sworn as you", "notes": []},
    "65": {"play": "Have done to this.", "notes": []},
    "66": {"play": "LADY MACBETH: If we should fail?", "notes": []},
    "67": {"play": "MACBETH: We fail!", "notes": []},
    "68": {"play": "But screw your courage to the sticking-place,", "notes": []},
    "69": {"play": "And we'll not fail. When Duncan is asleep--", "notes": []},
    "70": {"play": "Whereto the rather shall his day's hard journey", "notes": []},
    "71": {"play": "Soundly invite him--his two chamberlains", "notes": []},
    "72": {"play": "Will I with wine and wassail so convince", "notes": []},
    "73": {"play": "That memory, the warder of the brain,", "notes": []},
    "74": {"play": "Shall be a fume, and the receipt of reason", "notes": []},
    "75": {"play": "A limbeck only: when in swinish sleep", "notes": []},
    "76": {"play": "Their drenched natures lie as in a death,", "notes": []},
    "77": {"play": "What cannot you and I perform upon", "notes": []},
    "78": {"play": "The unguarded Duncan? what not put upon", "notes": []},
    "79": {"play": "His spongy officers, who shall bear the guilt", "notes": []},
    "80": {"play": "Of our great quell?", "notes": []},
    "81": {"play": "LADY MACBETH: Bring forth men-children only;", "notes": []},
    "82": {"play": "For thy undaunted mettle should compose", "notes": []},
    "83": {"play": "Nothing but males. Will it not be received,", "notes": []},
    "84": {"play": "When we have mark'd with blood those sleepy two", "notes": []},
    "85": {"play": "Of his own chamber and used their very daggers,", "notes": []},
    "86": {"play": "That they have done't?", "notes": []},
    "87": {"play": "MACBETH: Who dares receive it other,", "notes": []},
    "88": {"play": "As we shall make our griefs and clamour roar", "notes": []},
    "89": {"play": "Upon his death?", "notes": []},
    "90": {"play": "LADY MACBETH: I am settled, and bend up", "notes": []},
    "91": {"play": "Each corporal agent to this terrible feat.", "notes": []},
    "92": {"play": "Away, and mock the time with fairest show:", "notes": []},
    "93": {"play": "False face must hide what the false heart doth know.", "notes": []},
    "94": {"play": "[Exeunt]", "notes": []},
}

# Fix speaker mixups - lines 32-39 and 40-50 and 51-66 are swapped in MIT format
# Checking: MIT has LADY MACBETH: He has almost supp'd - so 32 is Lady Macbeth
# And MACBETH: We will proceed - so 35 is Macbeth
# Let me fix the speaker assignments to match the dialogue flow
FIXED_SCENE = {
    "1": {"play": "[Hautboys and torches. Enter a Sewer, and divers Servants with dishes and service, and pass over the stage. Then enter MACBETH]", "notes": []},
    "2": {"play": "MACBETH: If it were done when 'tis done, then 'twere well", "notes": []},
    "3": {"play": "It were done quickly: if the assassination", "notes": []},
    "4": {"play": "Could trammel up the consequence, and catch", "notes": []},
    "5": {"play": "With his surcease success; that but this blow", "notes": []},
    "6": {"play": "Might be the be-all and the end-all here,", "notes": []},
    "7": {"play": "But here, upon this bank and shoal of time,", "notes": []},
    "8": {"play": "We'ld jump the life to come. But in these cases", "notes": []},
    "9": {"play": "We still have judgment here; that we but teach", "notes": []},
    "10": {"play": "Bloody instructions, which, being taught, return", "notes": []},
    "11": {"play": "To plague the inventor: this even-handed justice", "notes": []},
    "12": {"play": "Commends the ingredients of our poison'd chalice", "notes": []},
    "13": {"play": "To our own lips. He's here in double trust;", "notes": []},
    "14": {"play": "First, as I am his kinsman and his subject,", "notes": []},
    "15": {"play": "Strong both against the deed; then, as his host,", "notes": []},
    "16": {"play": "Who should against his murderer shut the door,", "notes": []},
    "17": {"play": "Not bear the knife myself. Besides, this Duncan", "notes": []},
    "18": {"play": "Hath borne his faculties so meek, hath been", "notes": []},
    "19": {"play": "So clear in his great office, that his virtues", "notes": []},
    "20": {"play": "Will plead like angels, trumpet-tongued, against", "notes": []},
    "21": {"play": "The deep damnation of his taking-off;", "notes": []},
    "22": {"play": "And pity, like a naked new-born babe,", "notes": []},
    "23": {"play": "Striding the blast, or heaven's cherubim, horsed", "notes": []},
    "24": {"play": "Upon the sightless couriers of the air,", "notes": []},
    "25": {"play": "Shall blow the horrid deed in every eye,", "notes": []},
    "26": {"play": "That tears shall drown the wind. I have no spur", "notes": []},
    "27": {"play": "To prick the sides of my intent, but only", "notes": []},
    "28": {"play": "Vaulting ambition, which o'erleaps itself", "notes": []},
    "29": {"play": "And falls on the other.", "notes": []},
    "30": {"play": "[Enter LADY MACBETH]", "notes": []},
    "31": {"play": "LADY MACBETH: How now! what news?", "notes": []},
    "32": {"play": "MACBETH: He has almost supp'd: why have you left the chamber?", "notes": []},
    "33": {"play": "LADY MACBETH: Hath he ask'd for me?", "notes": []},
    "34": {"play": "MACBETH: Know you not he has?", "notes": []},
    "35": {"play": "MACBETH: We will proceed no further in this business:", "notes": []},
    "36": {"play": "He hath honour'd me of late; and I have bought", "notes": []},
    "37": {"play": "Golden opinions from all sorts of people,", "notes": []},
    "38": {"play": "Which would be worn now in their newest gloss,", "notes": []},
    "39": {"play": "Not cast aside so soon.", "notes": []},
    "40": {"play": "LADY MACBETH: Was the hope drunk", "notes": []},
    "41": {"play": "Wherein you dress'd yourself? hath it slept since?", "notes": []},
    "42": {"play": "And wakes it now, to look so green and pale", "notes": []},
    "43": {"play": "At what it did so freely? From this time", "notes": []},
    "44": {"play": "Such I account thy love. Art thou afeard", "notes": []},
    "45": {"play": "To be the same in thine own act and valour", "notes": []},
    "46": {"play": "As thou art in desire? Wouldst thou have that", "notes": []},
    "47": {"play": "Which thou esteem'st the ornament of life,", "notes": []},
    "48": {"play": "And live a coward in thine own esteem,", "notes": []},
    "49": {"play": "Letting 'I dare not' wait upon 'I would,'", "notes": []},
    "50": {"play": "Like the poor cat i' the adage?", "notes": []},
    "51": {"play": "MACBETH: Prithee, peace: I dare do all that may become a man;", "notes": []},
    "52": {"play": "Who dares do more is none.", "notes": []},
    "53": {"play": "LADY MACBETH: What beast was't, then,", "notes": []},
    "54": {"play": "That made you break this enterprise to me?", "notes": []},
    "55": {"play": "When you durst do it, then you were a man;", "notes": []},
    "56": {"play": "And, to be more than what you were, you would", "notes": []},
    "57": {"play": "Be so much more the man. Nor time nor place", "notes": []},
    "58": {"play": "Did then adhere, and yet you would make both:", "notes": []},
    "59": {"play": "They have made themselves, and that their fitness now", "notes": []},
    "60": {"play": "Does unmake you. I have given suck, and know", "notes": []},
    "61": {"play": "How tender 'tis to love the babe that milks me:", "notes": []},
    "62": {"play": "I would, while it was smiling in my face,", "notes": []},
    "63": {"play": "Have pluck'd my nipple from his boneless gums,", "notes": []},
    "64": {"play": "And dash'd the brains out, had I so sworn as you", "notes": []},
    "65": {"play": "Have done to this.", "notes": []},
    "66": {"play": "MACBETH: If we should fail?", "notes": []},
    "67": {"play": "LADY MACBETH: We fail!", "notes": []},
    "68": {"play": "But screw your courage to the sticking-place,", "notes": []},
    "69": {"play": "And we'll not fail. When Duncan is asleep--", "notes": []},
    "70": {"play": "Whereto the rather shall his day's hard journey", "notes": []},
    "71": {"play": "Soundly invite him--his two chamberlains", "notes": []},
    "72": {"play": "Will I with wine and wassail so convince", "notes": []},
    "73": {"play": "That memory, the warder of the brain,", "notes": []},
    "74": {"play": "Shall be a fume, and the receipt of reason", "notes": []},
    "75": {"play": "A limbeck only: when in swinish sleep", "notes": []},
    "76": {"play": "Their drenched natures lie as in a death,", "notes": []},
    "77": {"play": "What cannot you and I perform upon", "notes": []},
    "78": {"play": "The unguarded Duncan? what not put upon", "notes": []},
    "79": {"play": "His spongy officers, who shall bear the guilt", "notes": []},
    "80": {"play": "Of our great quell?", "notes": []},
    "81": {"play": "MACBETH: Bring forth men-children only;", "notes": []},
    "82": {"play": "For thy undaunted mettle should compose", "notes": []},
    "83": {"play": "Nothing but males. Will it not be received,", "notes": []},
    "84": {"play": "When we have mark'd with blood those sleepy two", "notes": []},
    "85": {"play": "Of his own chamber and used their very daggers,", "notes": []},
    "86": {"play": "That they have done't?", "notes": []},
    "87": {"play": "LADY MACBETH: Who dares receive it other,", "notes": []},
    "88": {"play": "As we shall make our griefs and clamour roar", "notes": []},
    "89": {"play": "Upon his death?", "notes": []},
    "90": {"play": "MACBETH: I am settled, and bend up", "notes": []},
    "91": {"play": "Each corporal agent to this terrible feat.", "notes": []},
    "92": {"play": "Away, and mock the time with fairest show:", "notes": []},
    "93": {"play": "False face must hide what the false heart doth know.", "notes": []},
    "94": {"play": "[Exeunt]", "notes": []},
}

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, "Public", "Data", "macbeth_notes_cleaned_play.json")

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "ACT 1, SCENE 7" in data:
        print("ACT 1, SCENE 7 already exists. Skipping.")
        return

    # Build new dict with scene inserted before ACT 2
    new_data = {}
    for key, value in data.items():
        if key == "ACT 2, SCENE 1":
            new_data["ACT 1, SCENE 7"] = FIXED_SCENE
        new_data[key] = value

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(new_data, f, indent=2, ensure_ascii=False)

    print("Added ACT 1, SCENE 7 to macbeth_notes_cleaned_play.json")

if __name__ == "__main__":
    main()
